# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('filer_id_raw', models.IntegerField(db_index=True)),
                ('xref_filer_id', models.CharField(max_length=32, null=True, db_index=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('committee_type', models.CharField(db_index=True, max_length=50, choices=[(b'cand', b'Candidate'), (b'pac', b'PAC'), (b'linked-pac', b'Non-Candidate Committee, linked to other committees')])),
                ('party', models.CharField(max_length=255, choices=[(b'16013', b'Americans Elect'), (b'16012', b'No party preference'), (b'16011', b'Unknown'), (b'16010', b'Natural law'), (b'16009', b'Non-partisan'), (b'16008', b'Libertarian'), (b'16007', b'Independent'), (b'16006', b'Peace and Freedom'), (b'16005', b'American Independent'), (b'16004', b'Reform'), (b'16003', b'Green'), (b'16002', b'Republican'), (b'16001', b'Democratic'), (b'0', b'N/A')])),
                ('status', models.CharField(max_length=255, null=True, choices=[(b'', b'N/A'), (b'N', b'Inactive'), (b'P', b'Pending'), (b'R', b'Revoked'), (b'S', b'Suspended'), (b'W', b'Withdrawn'), (b'Y', b'Active')])),
                ('level_of_government', models.CharField(max_length=255, null=True, choices=[(b'40501', b'Local'), (b'40502', b'State'), (b'40503', b'County'), (b'40504', b'Multi-county'), (b'40505', b'City'), (b'40506', b'Federal'), (b'40507', b'Superior court judge'), (b'0', b'N/A')])),
                ('effective_date', models.DateField(null=True)),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('filing_id_raw', models.IntegerField(db_index=True)),
                ('transaction_id', models.CharField(max_length=20, verbose_name=b'transaction ID', db_index=True)),
                ('amend_id', models.IntegerField(verbose_name=b'amendment', db_index=True)),
                ('backreference_transaction_id', models.CharField(max_length=20, verbose_name=b'backreference transaction ID', db_index=True)),
                ('is_crossreference', models.CharField(max_length=1, blank=True)),
                ('crossreference_schedule', models.CharField(max_length=2, blank=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('transaction_type', models.CharField(max_length=1, blank=True)),
                ('date_received', models.DateField(null=True)),
                ('contribution_description', models.CharField(max_length=90, blank=True)),
                ('amount', models.DecimalField(max_digits=14, decimal_places=2)),
                ('contributor_full_name', models.CharField(max_length=255)),
                ('contributor_is_person', models.BooleanField(default=False)),
                ('contributor_prefix', models.CharField(max_length=10, blank=True)),
                ('contributor_first_name', models.CharField(max_length=255, blank=True)),
                ('contributor_last_name', models.CharField(max_length=200, blank=True)),
                ('contributor_suffix', models.CharField(max_length=10, blank=True)),
                ('contributor_address_1', models.CharField(max_length=55, blank=True)),
                ('contributor_address_2', models.CharField(max_length=55, blank=True)),
                ('contributor_city', models.CharField(max_length=30, blank=True)),
                ('contributor_state', models.CharField(max_length=2, blank=True)),
                ('contributor_zipcode', models.CharField(max_length=10, blank=True)),
                ('contributor_occupation', models.CharField(max_length=60, blank=True)),
                ('contributor_employer', models.CharField(max_length=200, blank=True)),
                ('contributor_selfemployed', models.CharField(max_length=1, blank=True)),
                ('contributor_entity_type', models.CharField(blank=True, help_text=b'The type of entity that made that contribution', max_length=3, choices=[(b'', b'None'), (b'0', b'0'), (b'BNM', b'BNM'), (b'COM', b'Recipient committee'), (b'IND', b'Individual'), (b'OFF', b'OFF'), (b'OTH', b'Other'), (b'PTY', b'Political party'), (b'RCP', b'RCP'), (b'SCC', b'Small contributor committee')])),
                ('intermediary_prefix', models.CharField(max_length=10, blank=True)),
                ('intermediary_first_name', models.CharField(max_length=255, blank=True)),
                ('intermediary_last_name', models.CharField(max_length=200, blank=True)),
                ('intermediary_suffix', models.CharField(max_length=10, blank=True)),
                ('intermediary_address_1', models.CharField(max_length=55, blank=True)),
                ('intermediary_address_2', models.CharField(max_length=55, blank=True)),
                ('intermediary_city', models.CharField(max_length=30, blank=True)),
                ('intermediary_state', models.CharField(max_length=2, blank=True)),
                ('intermediary_zipcode', models.CharField(max_length=10, blank=True)),
                ('intermediary_occupation', models.CharField(max_length=60, blank=True)),
                ('intermediary_employer', models.CharField(max_length=200, blank=True)),
                ('intermediary_selfemployed', models.CharField(max_length=1, blank=True)),
                ('intermediary_committee_id', models.CharField(max_length=9, blank=True)),
                ('committee', models.ForeignKey(related_name=b'contributions_to', to='calaccess_campaign_browser.Committee')),
                ('contributor_committee', models.ForeignKey(related_name=b'contributions_from', to='calaccess_campaign_browser.Committee', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('name', models.IntegerField(serialize=False, primary_key=True, db_index=True)),
            ],
            options={
                'ordering': ('-name',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=50, choices=[(b'GENERAL', b'General'), (b'PRIMARY', b'Primary'), (b'RECALL', b'Recall'), (b'SPECIAL', b'Special'), (b'SPECIAL_RUNOFF', b'Special Runoff'), (b'OTHER', b'Other')])),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ('-year',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('amount', models.DecimalField(max_digits=16, decimal_places=2)),
                ('bakref_tid', models.CharField(max_length=50L, blank=True)),
                ('cmte_id', models.CharField(max_length=9L, blank=True)),
                ('cum_ytd', models.DecimalField(null=True, max_digits=16, decimal_places=2)),
                ('entity_cd', models.CharField(max_length=5L, blank=True)),
                ('expn_chkno', models.CharField(max_length=20L, blank=True)),
                ('expn_code', models.CharField(blank=True, max_length=3L, choices=[(b'CMP', b'campaign paraphernalia/misc.'), (b'CNS', b'campaign consultants'), (b'CTB', b'contribution (explain nonmonetary)*'), (b'CVC', b'civic donations'), (b'FIL', b'candidate filing/ballot fees'), (b'FND', b'fundraising events'), (b'IND', b'independent expenditure supporting/opposing others (explain)*'), (b'LEG', b'legal defense'), (b'LIT', b'campaign literature and mailings'), (b'MBR', b'member communications'), (b'MTG', b'meetings and appearances'), (b'OFC', b'office expenses'), (b'PET', b'petition circulating'), (b'PHO', b'phone banks'), (b'POL', b'polling and survey research'), (b'POS', b'postage, delivery and messenger services'), (b'PRO', b'professional services (legal, accounting)'), (b'PRT', b'print ads'), (b'RAD', b'radio airtime and production costs'), (b'RFD', b'returned contributions'), (b'SAL', b"campaign workers' salaries"), (b'TEL', b't.v. or cable airtime and production costs'), (b'TRC', b'candidate travel, lodging, and meals'), (b'TRS', b'staff/spouse travel, lodging, and meals'), (b'TSF', b'transfer between committees of the same candidate/sponsor'), (b'VOT', b'voter registration'), (b'WEB', b'information technology costs (internet, e-mail)')])),
                ('expn_date', models.DateField(null=True)),
                ('expn_dscr', models.CharField(max_length=400L, blank=True)),
                ('form_type', models.CharField(max_length=6L, blank=True)),
                ('g_from_e_f', models.CharField(max_length=1L, blank=True)),
                ('line_item', models.IntegerField()),
                ('memo_code', models.CharField(max_length=1L, blank=True)),
                ('memo_refno', models.CharField(max_length=20L, blank=True)),
                ('payee_adr1', models.CharField(max_length=55L, blank=True)),
                ('payee_adr2', models.CharField(max_length=55L, blank=True)),
                ('payee_city', models.CharField(max_length=30L, blank=True)),
                ('payee_namf', models.CharField(max_length=255L, blank=True)),
                ('payee_naml', models.CharField(max_length=200L, blank=True)),
                ('payee_nams', models.CharField(max_length=10L, blank=True)),
                ('payee_namt', models.CharField(max_length=10L, blank=True)),
                ('payee_st', models.CharField(max_length=2L, blank=True)),
                ('payee_zip4', models.CharField(max_length=10L, blank=True)),
                ('tran_id', models.CharField(max_length=20L, blank=True)),
                ('xref_match', models.CharField(max_length=1L, blank=True)),
                ('xref_schnm', models.CharField(max_length=2L, blank=True)),
                ('name', models.CharField(max_length=255)),
                ('raw_org_name', models.CharField(max_length=255)),
                ('person_flag', models.BooleanField(default=False)),
                ('org_id', models.IntegerField(null=True)),
                ('individual_id', models.IntegerField(null=True)),
                ('dupe', models.BooleanField(default=False)),
                ('committee', models.ForeignKey(to='calaccess_campaign_browser.Committee')),
                ('cycle', models.ForeignKey(to='calaccess_campaign_browser.Cycle')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Filer',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('filer_id_raw', models.IntegerField(db_index=True)),
                ('xref_filer_id', models.CharField(max_length=32, null=True, db_index=True)),
                ('filer_type', models.CharField(max_length=10, choices=[(b'pac', b'PAC'), (b'cand', b'Candidate')])),
                ('party', models.CharField(max_length=255, choices=[(b'16013', b'Americans Elect'), (b'16012', b'No party preference'), (b'16011', b'Unknown'), (b'16010', b'Natural law'), (b'16009', b'Non-partisan'), (b'16008', b'Libertarian'), (b'16007', b'Independent'), (b'16006', b'Peace and Freedom'), (b'16005', b'American Independent'), (b'16004', b'Reform'), (b'16003', b'Green'), (b'16002', b'Republican'), (b'16001', b'Democratic'), (b'0', b'N/A')])),
                ('status', models.CharField(max_length=255, null=True, choices=[(b'A', b'Active'), (b'ACTIVE', b'Active'), (b'INACTIVE', b'Inactive'), (b'N', b'Inactive'), (b'P', b'Pending'), (b'R', b'Revoked'), (b'S', b'Suspended'), (b'TERMINATED', b'Terminated'), (b'W', b'Withdrawn'), (b'Y', b'Active')])),
                ('effective_date', models.DateField(null=True)),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('filing_id_raw', models.IntegerField(verbose_name=b'filing ID', db_index=True)),
                ('amend_id', models.IntegerField(verbose_name=b'amendment', db_index=True)),
                ('form_type', models.CharField(db_index=True, max_length=7, choices=[(b'F497', b'F497: Late filing'), (b'F460', b'F460: Quarterly'), (b'F450', b'F450: Quarterly (Short)')])),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('date_received', models.DateField(null=True)),
                ('date_filed', models.DateField(null=True)),
                ('is_duplicate', models.BooleanField(default=False, help_text=b'A record that has either been superceded by an amendment or was filed unnecessarily. Should be excluded from most analysis.', db_index=True)),
                ('committee', models.ForeignKey(to='calaccess_campaign_browser.Committee')),
                ('cycle', models.ForeignKey(to='calaccess_campaign_browser.Cycle')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FilingPeriod',
            fields=[
                ('period_id', models.IntegerField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=25, blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deadline', models.DateField()),
            ],
            options={
                'ordering': ('-end_date',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=50, choices=[(b'GOVERNOR', b'Governor'), (b'LIEUTENANT_GOVERNOR', b'Lieutenant Governor'), (b'SECRETARY_OF_STATE', b'Secretary of State'), (b'CONTROLLER', b'Controller'), (b'TREASURER', b'Treasurer'), (b'ATTORNEY_GENERAL', b'Attorney General'), (b'SUPERINTENDENT_OF_PUBLIC_INSTRUCTION', b'Superintendent of Public Instruction'), (b'INSURANCE_COMMISSIONER', b'Insurance Commissioner'), (b'BOARD_OF_EQUALIZATION', b'Board of Equalization'), (b'SENATE', b'Senate'), (b'ASSEMBLY', b'Assembly'), (b'OTHER', b'Other')])),
                ('seat', models.IntegerField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('filing_id_raw', models.IntegerField(db_index=True)),
                ('amend_id', models.IntegerField(db_index=True)),
                ('itemized_monetary_contributions', models.DecimalField(default=None, null=True, max_digits=16, decimal_places=2)),
                ('unitemized_monetary_contributions', models.DecimalField(default=None, null=True, max_digits=16, decimal_places=2)),
                ('total_monetary_contributions', models.DecimalField(default=None, null=True, max_digits=16, decimal_places=2)),
                ('non_monetary_contributions', models.DecimalField(default=None, null=True, max_digits=16, decimal_places=2)),
                ('total_contributions', models.DecimalField(default=None, null=True, max_digits=16, decimal_places=2)),
                ('itemized_expenditures', models.DecimalField(default=None, null=True, max_digits=16, decimal_places=2)),
                ('unitemized_expenditures', models.DecimalField(default=None, null=True, max_digits=16, decimal_places=2)),
                ('total_expenditures', models.DecimalField(default=None, null=True, max_digits=16, decimal_places=2)),
                ('ending_cash_balance', models.DecimalField(default=None, null=True, max_digits=16, decimal_places=2)),
                ('outstanding_debts', models.DecimalField(default=None, null=True, max_digits=16, decimal_places=2)),
            ],
            options={
                'verbose_name_plural': 'summaries',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='filing',
            name='period',
            field=models.ForeignKey(to='calaccess_campaign_browser.FilingPeriod', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='expenditure',
            name='filing',
            field=models.ForeignKey(to='calaccess_campaign_browser.Filing'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='contribution',
            name='cycle',
            field=models.ForeignKey(to='calaccess_campaign_browser.Cycle'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='contribution',
            name='filing',
            field=models.ForeignKey(to='calaccess_campaign_browser.Filing'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='committee',
            name='filer',
            field=models.ForeignKey(to='calaccess_campaign_browser.Filer'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(to='calaccess_campaign_browser.Election'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='candidate',
            name='filer',
            field=models.ForeignKey(to='calaccess_campaign_browser.Filer'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='candidate',
            name='office',
            field=models.ForeignKey(to='calaccess_campaign_browser.Office'),
            preserve_default=True,
        ),
    ]
